version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ng02
    env_file:
    - ../.env
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/src
    - /home/ubuntu:/cert
    - ./nginx:/etc/nginx/conf.d
    depends_on:
    - web

  web:
    build: .
    container_name: reservoFeNewTestDeploy
    sysctls:
      net.core.somaxconn: 1024
    logging:
      options:
        max-size: "2m"
        max-file: "1"
    command: bash -c "
               python manage.py migrate && uwsgi --ini uwsgi.ini"
    env_file:
    - ../.env
    volumes:
    - ./:/src
    - /home/ubuntu/:/home
    expose:
    - "3000"
    tty: true

  redis:
    image: "redis:latest"
    container_name: feredis
    ports:
    - "6378:6379"

  celery:
    build: .
    container_name: feCelery
    env_file:
    - ../.env
    command: celery -A ProyectoFe.celery worker -B -l info
    volumes:
    - .:/src
    depends_on:
    - redis


