version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ng02
    env_file:
    - ../.env
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/src
    - /home/ubuntu:/cert
    - ./nginx:/etc/nginx/conf.d
    depends_on:
    - web

  db:
    container_name: postgres_vuxkoapp
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    image: public.ecr.aws/i0m6d4r8/libpoblete:latest
    container_name: vuxkoWebDeploy
    sysctls:
      net.core.somaxconn: 1024
    logging:
      options:
        max-size: "2m"
        max-file: "1"
    command: bash -c "
               python manage.py migrate && uwsgi --ini uwsgi.ini"
    env_file:
    - ../.env
    volumes:
    - ./:/code
    - /home/ubuntu/:/home
    expose:
    - "3000"
    tty: true
    depends_on:
    - db
    - redis

  redis:
    image: "redis:latest"
    container_name: vuxkoWebredis
    ports:
    - "6378:6379"

  celery:
    image: public.ecr.aws/i0m6d4r8/libpoblete:latest
    container_name: vuxkoWebCelery
    env_file:
    - ../.env
    command: celery -A vuxkotrade.celery worker -B -l info
    volumes:
    - .:/code
    depends_on:
    - redis


