# Generated by Django 4.0.6 on 2022-07-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='temp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
