# Generated by Django 4.0.6 on 2022-08-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_bot_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
