# Generated by Django 4.0.6 on 2022-08-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0003_bot_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
